server:
 port: 7787
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: root
  url: jdbc:mysql://127.0.0.1/spring_cloud_order_system?characterEncoding=utf-8&useSSL=false
